name: Publish Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: montransit
          password: ${{ secrets.MT_DOCKER_PASSWORD }}
      -
        name: Checkout another repo
        uses: actions/checkout@v2
        with:
          repository: mtransitapps/ca-montreal-bixi-bike-gradle
          ref: use_docker_image
          path: /tmp/mt_project
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mtransitapps/docker-image-android:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}